### ISSUE TITLE
The project is not exportable

### ISSUE THREAD

**Issue by vinid223** [IntuitDeveloper/OAuth2-Dotnet_UsingSDK#1]
When downloading the repository, the solution can't find the project.

When loading the project manually all the references are unavailable.

The project can't find the scopeVal with the ConfigurationManager. I can see that they are in your build folder and not in the project configuration.

After commenting all the non working code, when I click on "Sign In With Intuit" or clicking on "Connect to QuickBooks" I get the error :

"We're sorry!
We're experiencing some problems. Please try again later."

**Comment by nimisha84** [comment]
Which Framework did you target? It should be 4.6.1.
scopeVal is set within the project. It is not a part of Config.
Did you setup the correct redirectURI(callback) in your config as well as in the developer portal? Please copy the url from the top of the browser and paste here.

**Comment by vinid223** [comment]
The Framework target is already set to 4.6.1 in the project.
I had to manually add the scopeVal into the Web.config for the app to not crash while getting the values.
The callback is the local one that I use for opening the page.

This is the URL that the project generated after I changed the callback url and the client_id that I took from the dev app(OAuth Consumer Key) : https://appcenter.intuit.com/connect/oauth2?client_id=qyprdSKWHqLhrGVsJhQmq4ZGy8tMVu&response_type=code&scope=openid%20email%20profile%20phone%20address&redirect_uri=http%3A%2F%2Flocalhost%3A49397%2FOAuth2Manager.aspx&state=-vpqjtVpCk5-VaidGSMqSpGyTgja5q5GXlDIzD7wkJ0

**Comment by nimisha84** [comment]
Did you configure the same callback url -http://localhost:49397/OAuth2Manager.aspx in your dev app settings on developer.intuit.com?

**Comment by vinid223** [comment]
@nimisha84 I am trying but I can't. First I don't really know where to put the callback url because there is no field named like that in the app settings. Also, I've tried to put an URL into all the fields that could be an URL but I get an invalid URL error in each fields

**Comment by vinid223** [comment]
I've noticed that I can't put localhost as a domain in the app config.

**Comment by vinid223** [comment]
I successfully add an url but I needed to change the project url from localhost to something else for the app settings to accept it. Even after I change that and add all the callback url in the app settings in developper.intuit.com and in the project, I still get the same error "We're experiencing some problems. Please try again later."

**Comment by nimisha84** [comment]
Hi, 
I guess there is some confusion around what I am trying to convey. 
Set your client id, client secret , redirectUrl and logpath in app.config or web.config.
The redirectUrl can be a http localhost url like this-http://localhost:52626/TestOAuth2_WithSDK.aspx

Then go to developer.intuit.com->Login->My app->Go to Keys tab of the app.
There is a section for Redirect Uris under development keys section. 
Add the same http://localhost:52626/TestOAuth2_WithSDK.aspx url there.

Please note that http://localhost:52626/TestOAuth2_WithSDK.aspx is just for reference.
You need to run your .net code and see what is the localhost url and then setup redirect url in the config as well on developer portal->app keys page.

**Comment by vinid223** [comment]
I don't see any sections for Redirect Uris. I had to go to the settings to set the agreement and Privacy Policy to have access to the productions keys but there is nothing more

**Comment by nimisha84** [comment]
Did you create a new developer account recently or were you an existing developer having some apps?
Only new developer accounts can create new apps for Oauth2 and can see correct keys and redirecturl settings for Oauth2

**Comment by vinid223** [comment]
It is an old account for the dev team that already have an app

**Comment by nimisha84** [comment]
So, in order to use Oauth2 then, you will have to register on developer portal with a new email id.
Then create an app.
Then you should see the correct keys and redirectUrl settings.

**Comment by vinid223** [comment]
Now it is working, thanks.

**Comment by nimisha84** [comment]
Great. Closing this issue.
