### ISSUE TITLE
Cloned Project does not run

### ISSUE THREAD

**Issue by hhalstrom** [IntuitDeveloper/OAuth2-Dotnet_UsingSDK#2]
After having downloaded this project as a .zip file, or cloned using CMD, and extracting all the files this project does not run.
Upon opening the .sln file the first error reads as...

> C:\Users\nshrivastava\Documents\GitHub\V3-DotNet-SDK.git\IPPDotNetDevKitCSV3\Samples\SampleAppOAuth2Lib\SampleAppOAuth2_UsingSDK.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\nshrivastava\Documents\GitHub\V3-DotNet-SDK.git\IPPDotNetDevKitCSV3\Samples\SampleAppOAuth2Lib\SampleAppOAuth2_UsingSDK.csproj'.  C:\Users\nshrivastava\Documents\GitHub\V3-DotNet-SDK.git\IPPDotNetDevKitCSV3\Samples\SampleAppOAuth2Lib\SampleAppOAuth2_UsingSDK.csproj

The simple fix is to relocate the file path to the csproj file provided by this repo "OAuth2_SampleApp_Dotnet_UsingSDK.csproj" (where ever the project exists on your drive)

Then, reload the project.

Next error, which I am not sure if this is a problem with my environment or not (I suspect not) it reads...

> The C# project "OAuth2_SampleApp_Dotnet_UsingSDK" is targeting ".NETFramework,Version=v4.6.1", which is not installed on this machine. To proceed, select an option below.

My options are the change the target framework to v4.5.2 or to download v4.6.1
After downloading the correct version, Windows tells me that I already have v4.6.1 installed... So, I am not sure what that is trying to telling me. Possibly the project looking for the correct files under your personal PC's User files, like before? (C:\Users\nshrivastava\...)

So, I try the option to change the target version to v4.5.2.
This lets me open the solution without errors.

Then, after updating clientId, clientSecret, logPath, and redirectURI and rebuilding the solution I get the error of...

> This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.0\build\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props.	OAuth2_SampleApp_Dotnet_UsingSDK	C:\Development\OAuth2-Dotnet_UsingSDK-master\OAuth2_SampleApp_Dotnet\OAuth2_SampleApp_Dotnet_UsingSDK.csproj

Making sure I have the "Allow nuget to restore packages" option is active I right-click on the solution and hit "Restore NuGet Packages".
The output after this is "All packages are already installed and there is nothing to restore"

I also checked and noticed that a "packages" folder did get downloaded along with the rest of this repo and on further investigation it looks like the folder "\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.0\build"
does not exist and only "content" and "tools" can be found.

I can't seem to get this example to run, is there any help that could be provided to get this to run?

**Comment by nimisha84** [comment]
I see, one other user reported same issues. When I try to download the zip and replicate the issues you/other person reported, I can't replicate. However what I will do is create a new clean project and then update the github repo.
Hopefully that should fix the issue. Will update you then. Can you wait until that? Hopefully a day.

**Comment by hhalstrom** [comment]
Yes, I look forward to the update.

Let me know if you need any info from me.

**Comment by nimisha84** [comment]
Please delete the old code and clone again. Retry and let me know if you see any issues

**Comment by hhalstrom** [comment]
Things are working more smoothly this time. But...

After getting the new files and extracting I have received the same "target framework" issue, but I am able to work around that.

My other error now is...

> The "Microsoft.CodeAnalysis.BuildTasks.Csc" task could not be loaded from the assembly C:\Development\OAuth2-Dotnet_UsingSDK-master\OAuth2-Dotnet_UsingSDK\packages\Microsoft.Net.Compilers.1.3.2\build\..\tools\Microsoft.Build.Tasks.CodeAnalysis.dll. Could not load file or assembly 'file:///C:\Development\OAuth2-Dotnet_UsingSDK-master\OAuth2-Dotnet_UsingSDK\packages\Microsoft.Net.Compilers.1.3.2\tools\Microsoft.Build.Tasks.CodeAnalysis.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	OAuth2-Dotnet_UsingSDK		

I have tried deleting the 'packages' folder and ran 'Restore NuGet Packages'. This ensures the file 'Microsoft.Build.Tasks.CodeAnalysis.dll' is in the correct place in the path. But, I rebuild the Solution and I get the same error again. So, judging by the error message I would think one of it's dependencies must be missing.

Unfortunately I am leaving for a few days so I won't be able to address any fixes until Monday.

I hope what I provided helps track down the issues.

**Comment by nimisha84** [comment]
Thanks. Let me take a look at this.

**Comment by nimisha84** [comment]
I updated the Microsoft.Net.Compilers lib too and refreshed the packages folder.
Let me know if you still see issues. Not sure what is wrong with this repo. I am not replicate any of the issues on my env though (strange).
https://stackoverflow.com/questions/32150204/buildtasks-csc-task-could-not-be-loaded-from-the-assembly

**Comment by sm-g** [comment]
Why you ever commit packages and bin dir?! And .suo?

Also I had to fix
  ```
-<package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.3" targetFramework="net452" />
  +<package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.5" targetFramework="net461" />
```
and reinstall Microsoft.Net.Compilers (some paths changes after that)

**Comment by nimisha84** [comment]
HI @sm-g - Can you do a pull for your changes so that I can merge?

**Comment by nimisha84** [comment]
Never mind, I made the changes. Please retry at your end if you still see issues with this repo and report here.
