### ISSUE TITLE
Setting DiscoveryAuthority

### ISSUE THREAD

**Issue by robfarmergt** [IntuitDeveloper/OAuth2-Dotnet_UsingSDK#3]
I'm trying to retrieve the discovery document but I'm getting an error in the `DiscoveryClient` that states `Issuer name does not match authority: https://oauth.platform.intuit.com/op/v1`

I see in the web.config that there is a setting but I've added it and it doesn't seem to be using it. I'm using a .NET Core web app that targets .netstandard 1.3.

Is there another way to set the url for the Authority or to bypass the check? The code example starting on line `288` is what I'm using:

```
DiscoveryPolicy dpolicy = new DiscoveryPolicy();
dpolicy.RequireHttps = true;
dpolicy.ValidateIssuerName = true;


//Assign the Sandbox Discovery url for the Apps' Dev clientid and clientsecret that you use
//Or
//Assign the Production Discovery url for the Apps' Production clientid and clientsecret that you use

if (discoveryUrl != null && clientID != null && clientSecret != null)
{
	discoveryClient = new DiscoveryClient(discoveryUrl);
}

doc = await discoveryClient.GetAsync();
```

Also `dpolicy` doesn't appear to be being used in the example.

**Comment by bdysert** [comment]
Hey Rob. Have you made any progress? I'm in the same piece of code, but when I hit the call to "discoveryClient.GetAsync()" the program quietly terminates. Have you encountered that?

**Comment by nbhambhani** [comment]
In the config file of your project under appSettings section, 
```
<appSettings>
    <add key="DiscoveryAuthority" value="https://oauth.platform.intuit.com/op/v1"/>
</appSettings>
```
these lines should be added otherwise you might get error `Issuer name does not match authority: https://oauth.platform.intuit.com/op/v1`

**Comment by robfarmergt** [comment]
@nbhambhani This is a .NET Core project and there is no XML config file.

**Comment by nbhambhani** [comment]
@robfarmergt Can you check if [this](https://github.com/ehalsey-quickbooks/QuickBooksASPNetCore2OpenIDConnect) sample works for you?

**Comment by nbhambhani** [comment]
@robfarmergt  was this resolved for you?
