### ISSUE TITLE
Discovery Error, Missing authorizationEndpoint url

### ISSUE THREAD

**Issue by manovraresoft** [IntuitDeveloper/OAuth2-Dotnet_UsingSDK#6]
I have defined my ClientID, Secret, and Endpoint URIs in the webconfig and they match the settings in QB API settings in my sandbox.

In my logs: 

7/3/2018 8:42:44 AM: Fetching Discovery Data..
7/3/2018 8:42:46 AM: Discovery error.
7/3/2018 8:42:46 AM: Intiating OAuth2 call to get code..
7/3/2018 8:42:46 AM: Setting up Authorize url.
7/3/2018 8:42:46 AM: Missing authorizationEndpoint url!.

I believe there is something wrong with the example or it is not configured correctly with QB.  The intro says I add these things to the web.config and I am able to run.

![image](https://user-images.githubusercontent.com/2041397/42221737-1d9747f4-7ea1-11e8-8018-880a5a04c905.png)

**Comment by nbhambhani** [comment]
@manovraresoft what's the SDK version you're using in the sample?

**Comment by nbhambhani** [comment]
@manovraresoft  This is most likely TLS issue. We accept only TLS1.2 requests and anything other than this will not be allowed by our servers.
